var manifest = [
    {
        src:"assets/assets.json",
        forSpritesheet:"assets"
    },
    {
        src:"assets/assets.png",
        id:"assets"
    },
    {
        src:"assets/overworld.ogg",
        id:"bgmusic",
        data:4
    },
    {
        src:"sounds/jump.ogg",
        id:"jump",
        data:1
    },
    {
        src:"sounds/titlescreen.ogg",
        id:"title",
        data:5
    },
    {
        src:"sounds/gameover.ogg",
        id:"gameover",
        data:5
    },
    {
        src:"sounds/key.ogg",
        id:"key",
        data:5
    },
    {
        src:"sounds/munch.ogg",
        id:"crunch",
        data:2
    },
    {
        src:"sounds/death.ogg",
        id:"death",
        data:3
    },
    {
        src:"mapTest/waffle.png",
        id:"waffle.png",
        bitmap:true
    },
    {
        src:"mapTest/waffleSyrup.png",
        id:"waffleSyrup.png",
        bitmap:true
    },
    {
        src:"mapTest/pancake.png",
        id:"pancake.png",
        bitmap:true
    },
    {
        src:"mapTest/pancake_leftend.png",
        id:"pancake_leftend.png",
        bitmap:true
    },
    {
        src:"mapTest/pancake_rightend.png",
        id:"pancake_rightend.png",
        bitmap:true
    },
    {
        src:"mapTest/key.png",
        id:"key.png",
        bitmap:true
    },
    {
        src:"mapTest/forkNknife.png",
        id:"forkNknife.png",
        bitmap:true
    },
    {
        src:"mapTest/border.png",
        id:"border.png",
        bitmap:true
    },
    {
        src:"assets/logo.png",
        id:"logo",
        bitmap:true
    },
    {
        src:"assets/btnStart.png",
        id:"btnStart",
        bitmap:true
    },
    {
        src:"assets/btnStart_clicked.png",
        id:"btnStart_clicked",
        bitmap:true
    },
    {
        src:"assets/gameOverTitle.png",
        id:"Game Over",
        bitmap:true
    },
    {
        src:"assets/btnRestart.png",
        id:"btnRestart",
        bitmap:true
    },
    {
        src:"assets/btnRestart_clicked.png",
        id:"btnRestart_clicked",
        bitmap:true
    },
    {
        src:"assets/btnReset.png",
        id:"btnReset",
        bitmap:true
    },
    {
        src:"assets/btnReset_clicked.png",
        id:"btnReset_clicked",
        bitmap:true
    },
    {
        src:"assets/winTitle.png",
        id:"winTitle",
        bitmap:true
    }
];