var manifest = [
    {
        src:"assets/assets.json",
        forSpritesheet:"assets"
    },
    {
        src:"assets/assets.png",
        id:"assets"
    },
    {
        src:"assets/overworld.ogg",
        id:"bgmusic",
        data:4
    },
    {
        src:"sounds/jump.ogg",
        id:"jump",
        data:1
    },
    {
        src:"sounds/munch.ogg",
        id:"crunch",
        data:2
    },
    {
        src:"sounds/death.ogg",
        id:"death",
        data:3
    },
    {
        src:"mapTest/waffle.png",
        id:"waffle.png",
        bitmap:true
    },
    {
        src:"mapTest/waffleSyrup.png",
        id:"waffleSyrup.png",
        bitmap:true
    },
    {
        src:"mapTest/pancake.png",
        id:"pancake.png",
        bitmap:true
    },
    {
        src:"mapTest/pancake_leftend.png",
        id:"pancake_leftend.png",
        bitmap:true
    },
    {
        src:"mapTest/pancake_rightend.png",
        id:"pancake_rightend.png",
        bitmap:true
    },
    {
        src:"mapTest/key.png",
        id:"key.png",
        bitmap:true
    },
    {
        src:"mapTest/forkNknife.png",
        id:"forkNknife.png",
        bitmap:true
    },
    {
        src:"mapTest/border.png",
        id:"border.png",
        bitmap:true
    }
];